# Generated by Django 3.0.3 on 2021-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='meter_status_v1_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='meter_status_v2_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='reader_status_v1_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='reader_status_v2_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
