# Generated by Django 3.0.3 on 2021-03-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0002_auto_20210311_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationassignment',
            name='validator1_id',
        ),
        migrations.RemoveField(
            model_name='validationassignment',
            name='validator2_id',
        ),
    ]
