# Generated by Django 3.0.3 on 2021-05-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0003_routetaskassignment_utility_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='reader_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
