# Generated by Django 3.0.3 on 2021-03-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0003_auto_20210311_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationassignment',
            name='validator1_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationassignment',
            name='validator2_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
