# Generated by Django 3.0.11 on 2021-03-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0002_auto_20210318_1109'),
        ('meter_data_management', '0003_remove_smartmeterconfiguration_request_parameter'),
    ]

    operations = [
    ]
