# Generated by Django 3.0.3 on 2021-03-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0004_merge_20210320_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartmeterconfiguration',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
