# Generated by Django 3.0.3 on 2021-03-12 04:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0004_auto_20210311_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='occurs_on',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
