# Generated by Django 3.0.3 on 2021-05-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0004_auto_20210521_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='state',
            field=models.IntegerField(choices=[(0, 'NOT-ASSIGNED'), (1, 'ASSIGNED')], default=0),
        ),
    ]
