# Generated by Django 3.0.11 on 2021-03-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0004_merge_20210319_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardtemplate',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartmeterconfiguration',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validationassignment',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
