# Generated by Django 3.0.3 on 2021-06-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0005_meter_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='device_no',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
