# Generated by Django 3.0.11 on 2021-03-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0005_auto_20210322_0718'),
        ('meter_data_management', '0005_auto_20210323_1123'),
    ]

    operations = [
    ]
