# Generated by Django 3.0.3 on 2021-03-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0005_auto_20210312_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routetaskassignment',
            name='dispatch_status',
            field=models.IntegerField(choices=[(0, 'NOT-DISPATCHED'), (1, 'IN-PROGRESS'), (2, 'STARTED'), (3, 'DISPATCHED'), (4, 'PARTIAL'), (5, 'ASSIGN-FAIL'), (6, 'DE-ASSIGN-FAIL'), (7, 'COMPLETED')], default=0),
        ),
    ]
