# Generated by Django 3.0.3 on 2021-06-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0006_meter_device_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulelog',
            name='schedule_log_status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'IN-PROGRESS'), (2, 'COMPLETED')], default=0),
        ),
    ]
