# Generated by Django 3.0.3 on 2021-03-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0006_auto_20210313_0613'),
        ('meter_data_management', '0006_auto_20210312_1542'),
    ]

    operations = [
    ]
