# Generated by Django 3.0.3 on 2021-03-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0006_auto_20210315_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
