# Generated by Django 3.0.3 on 2021-03-24 05:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('utility', '0005_utilitymaster_user_id'),
        ('meter_data_management', '0006_merge_20210323_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_string', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('schedule_log_id', models.BigIntegerField(blank=True, null=True)),
                ('read_cycle_id', models.BigIntegerField(blank=True, null=True)),
                ('route_id', models.BigIntegerField()),
                ('state', models.IntegerField(choices=[(0, 'NOT-SENT'), (1, 'SENT'), (2, 'RECEIVED'), (3, 'ACCEPTED'), (4, 'REJECTED'), (5, 'FAILED')], default=0)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.TenantMaster')),
                ('utility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.UtilityMaster')),
            ],
        ),
    ]
