# Generated by Django 3.0.3 on 2021-03-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0008_consumerdetail_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerdetail',
            name='is_spot_bill',
            field=models.BooleanField(default=False),
        ),
    ]
