# Generated by Django 3.0.3 on 2021-06-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0008_newconsumerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='newconsumerdetail',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newconsumerdetail',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newconsumerdetail',
            name='is_discard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newconsumerdetail',
            name='consumer_no',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newconsumerdetail',
            name='meter_no',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
