# Generated by Django 3.0.3 on 2021-03-30 10:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_utilitymaster_user_id'),
        ('tenant', '0001_initial'),
        ('meter_data_management', '0009_consumerdetail_is_spot_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_string', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('consumer_detail_id', models.BigIntegerField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=200, null=True)),
                ('consumption', models.CharField(blank=True, max_length=200, null=True)),
                ('consumption_charges', models.CharField(blank=True, max_length=200, null=True)),
                ('basic_price', models.CharField(blank=True, max_length=200, null=True)),
                ('vat_percentage', models.CharField(blank=True, max_length=200, null=True)),
                ('total_price', models.CharField(blank=True, max_length=200, null=True)),
                ('net_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_balance', models.CharField(blank=True, max_length=200, null=True)),
                ('current_charges', models.CharField(blank=True, max_length=200, null=True)),
                ('emi_security_deposit', models.CharField(blank=True, max_length=200, null=True)),
                ('current_emi_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('remaining_emi_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('bill_period_from', models.DateTimeField(blank=True, null=True)),
                ('bill_period_to', models.DateTimeField(blank=True, null=True)),
                ('before_due_date', models.DateTimeField(blank=True, null=True)),
                ('after_due_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_adjusted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.TenantMaster')),
                ('utility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.UtilityMaster')),
            ],
        ),
    ]
