# Generated by Django 3.0.3 on 2021-03-31 05:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0010_spotbill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotbill',
            name='after_due_date',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='basic_price',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='before_due_date',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='bill_period_from',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='bill_period_to',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='consumption_charges',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='current_charges',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='current_emi_amount',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='emi_security_deposit',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='previous_balance',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='remaining_emi_amount',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='spotbill',
            name='vat_percentage',
        ),
        migrations.AddField(
            model_name='spotbill',
            name='rate_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spotbill',
            name='spot_bill_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
