# Generated by Django 3.0.3 on 2021-03-31 10:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0011_auto_20210331_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='is_spot_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='spot_bill_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
