# Generated by Django 3.0.3 on 2021-04-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0012_auto_20210331_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulelog',
            name='schedule_log_status',
        ),
        migrations.AddField(
            model_name='schedulelog',
            name='state',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'NO-DATA'), (2, 'PARTIAL'), (3, 'IN-PROGRESS'), (4, 'COMPLETED'), (5, 'ARCHIVED')], default=0),
        ),
    ]
