# Generated by Django 3.0.3 on 2021-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0013_auto_20210401_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulelog',
            name='state',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'NO-DATA'), (2, 'IN-PROGRESS'), (3, 'PARTIAL'), (4, 'COMPLETED'), (5, 'ARCHIVED')], default=0),
        ),
    ]
