# Generated by Django 3.0.3 on 2021-04-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0013_auto_20210401_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routetaskassignment',
            name='dispatch_status',
        ),
        migrations.AddField(
            model_name='routetaskassignment',
            name='state',
            field=models.IntegerField(choices=[(0, 'NOT-DISPATCHED'), (1, 'IN-PROGRESS'), (2, 'STARTED'), (3, 'DISPATCHED'), (4, 'PARTIAL'), (5, 'ASSIGN-FAIL'), (6, 'DE-ASSIGN-FAIL'), (7, 'COMPLETED'), (8, 'ARCHIVED')], default=0),
        ),
        migrations.AlterField(
            model_name='schedulelog',
            name='state',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'NO-DATA'), (2, 'IN-PROGRESS'), (3, 'PARTIAL'), (4, 'COMPLETED'), (5, 'ARCHIVED')], default=0),
        ),
    ]
