# Generated by Django 3.0.11 on 2021-04-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0008_auto_20210330_1649'),
        ('meter_data_management', '0014_auto_20210402_0540'),
    ]

    operations = [
    ]
