# Generated by Django 3.0.3 on 2021-04-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0014_auto_20210402_0540'),
        ('meter_data_management', '0014_auto_20210402_1120'),
    ]

    operations = [
    ]
