# Generated by Django 3.0.11 on 2021-04-23 05:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data_management', '0015_merge_20210406_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readcycle',
            name='route_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
