# Generated by Django 3.0.3 on 2021-03-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 658678), null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 658678), null=True),
        ),
        migrations.AlterField(
            model_name='assetamccontract',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 662703), null=True),
        ),
        migrations.AlterField(
            model_name='assetamccontract',
            name='effective_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 662703), null=True),
        ),
        migrations.AlterField(
            model_name='assetamccontract',
            name='effective_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 662703), null=True),
        ),
        migrations.AlterField(
            model_name='assetamccontract',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 662703), null=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 658678), null=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 658678), null=True),
        ),
        migrations.AlterField(
            model_name='assetservicehistory',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 662703), null=True),
        ),
        migrations.AlterField(
            model_name='assetservicehistory',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 662703), null=True),
        ),
        migrations.AlterField(
            model_name='assetservicehistorystatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 666714), null=True),
        ),
        migrations.AlterField(
            model_name='assetservicehistorystatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 666714), null=True),
        ),
        migrations.AlterField(
            model_name='assetstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 654605), null=True),
        ),
        migrations.AlterField(
            model_name='assetstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 654605), null=True),
        ),
        migrations.AlterField(
            model_name='assetsubcategory',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 658678), null=True),
        ),
        migrations.AlterField(
            model_name='assetsubcategory',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 658678), null=True),
        ),
        migrations.AlterField(
            model_name='asssetinsurance',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 662703), null=True),
        ),
        migrations.AlterField(
            model_name='asssetinsurance',
            name='effective_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 662703), null=True),
        ),
        migrations.AlterField(
            model_name='asssetinsurance',
            name='effective_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 662703), null=True),
        ),
        migrations.AlterField(
            model_name='asssetinsurance',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 662703), null=True),
        ),
        migrations.AlterField(
            model_name='resourceassign',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 666714), null=True),
        ),
        migrations.AlterField(
            model_name='resourceassign',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 666714), null=True),
        ),
        migrations.AlterField(
            model_name='sopassign',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 670711), null=True),
        ),
        migrations.AlterField(
            model_name='sopassign',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 670711), null=True),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 670711), null=True),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 670711), null=True),
        ),
    ]
