# Generated by Django 3.0.3 on 2021-03-08 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcharges',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 35375), null=True),
        ),
        migrations.AlterField(
            model_name='additionalcharges',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 35375), null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 37370), null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 37370), null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 38367), null=True),
        ),
        migrations.AlterField(
            model_name='billcycle',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 30388), null=True),
        ),
        migrations.AlterField(
            model_name='billcycle',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 30388), null=True),
        ),
        migrations.AlterField(
            model_name='billfrequency',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 31386), null=True),
        ),
        migrations.AlterField(
            model_name='billfrequency',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 31386), null=True),
        ),
        migrations.AlterField(
            model_name='billmonth',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 21412), null=True),
        ),
        migrations.AlterField(
            model_name='billmonth',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 21412), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='conversion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 9, 963669), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 9, 963669), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='current_reading_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 9, 963669), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 9, 963669), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='invoice_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 9, 963669), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='previous_reading_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 9, 963669), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 9, 963669), null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 37370), null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 37370), null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 36372), null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 37370), null=True),
        ),
        migrations.AlterField(
            model_name='schedulebill',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 34378), null=True),
        ),
        migrations.AlterField(
            model_name='schedulebill',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 34378), null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 36372), null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 7, 36372), null=True),
        ),
    ]
