# Generated by Django 3.0.3 on 2021-03-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20210322_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='state',
            field=models.BigIntegerField(choices=[(0, 'CREATED'), (1, 'UN BILLED'), (2, 'IN PROGRESS'), (3, 'PARTIAL'), (4, 'HOLD'), (5, 'COMPLETED'), (6, 'APPROVED'), (7, 'ARCHIVED')], default=0),
        ),
    ]
