# Generated by Django 3.0.3 on 2021-03-12 07:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20210312_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcycle',
            name='route_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
