# Generated by Django 3.0.3 on 2021-03-10 07:44

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0021_auto_20210310_1314'),
        ('utility', '0018_auto_20210310_1314'),
        ('billing', '0002_auto_20210308_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcycle',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='billcycle',
            name='route_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='additionalcharges',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 678708), null=True),
        ),
        migrations.AlterField(
            model_name='additionalcharges',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 678708), null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 682709), null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 682709), null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 682709), null=True),
        ),
        migrations.AlterField(
            model_name='billcycle',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 674710), null=True),
        ),
        migrations.AlterField(
            model_name='billcycle',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 674710), null=True),
        ),
        migrations.AlterField(
            model_name='billfrequency',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 674710), null=True),
        ),
        migrations.AlterField(
            model_name='billfrequency',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 674710), null=True),
        ),
        migrations.AlterField(
            model_name='billmonth',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 670711), null=True),
        ),
        migrations.AlterField(
            model_name='billmonth',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 674710), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='conversion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 246710), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 246710), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='current_reading_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 246710), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 246710), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='invoice_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 246710), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='previous_reading_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 246710), null=True),
        ),
        migrations.AlterField(
            model_name='invoicebill',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 246710), null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 682709), null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 682709), null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 682709), null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 682709), null=True),
        ),
        migrations.AlterField(
            model_name='schedulebill',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 678708), null=True),
        ),
        migrations.AlterField(
            model_name='schedulebill',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 678708), null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 678708), null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 678708), null=True),
        ),
        migrations.CreateModel(
            name='ScheduleBillLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_string', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('schedule_bill_id', models.BigIntegerField()),
                ('bill_cycle_id', models.BigIntegerField()),
                ('recurring_id', models.BigIntegerField(blank=True, null=True)),
                ('utility_product_id', models.BigIntegerField(blank=True, null=True)),
                ('schedule_bill_log_status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'COMPLETED'), (2, 'INPROGRESS')], default=0)),
                ('date_and_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.TenantMaster')),
                ('utility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.UtilityMaster')),
            ],
        ),
        migrations.CreateModel(
            name='BillConsumerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_string', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('consumer_id', models.BigIntegerField(blank=True, null=True)),
                ('meter_id', models.BigIntegerField(blank=True, null=True)),
                ('bill_schedule_log_id', models.BigIntegerField(blank=True, null=True)),
                ('bill_cycle_id', models.BigIntegerField(blank=True, null=True)),
                ('route_id', models.BigIntegerField(blank=True, null=True)),
                ('premise_id', models.BigIntegerField(blank=True, null=True)),
                ('utility_product_id', models.BigIntegerField(blank=True, null=True)),
                ('consumer_no', models.CharField(blank=True, max_length=200, null=True)),
                ('meter_no', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.TenantMaster')),
                ('utility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.UtilityMaster')),
            ],
        ),
    ]
