# Generated by Django 3.0.3 on 2021-04-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20210420_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
