# Generated by Django 3.0.3 on 2021-04-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetemplate',
            name='template',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
    ]
