# Generated by Django 3.0.11 on 2021-04-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20210422_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='https://smart360-bucket.s3.amazonaws.com/MRBD/'),
        ),
    ]
