# Generated by Django 3.0.3 on 2021-04-23 09:44

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20210422_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='link',
        ),
        migrations.AlterField(
            model_name='bill',
            name='qr_code',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
