# Generated by Django 3.0.3 on 2021-04-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_fixedcharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedcharges',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
