# Generated by Django 3.0.11 on 2021-04-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20210423_0951'),
        ('billing', '0006_auto_20210424_1941'),
    ]

    operations = [
    ]
