# Generated by Django 3.0.3 on 2021-04-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_fixedcharges_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedcharges',
            old_name='meter_id',
            new_name='meter_no',
        ),
    ]
