# Generated by Django 3.0.3 on 2021-04-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_billinvoicesection_billinvoicesectionmaster_renderinvoicetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renderinvoicetemplate',
            name='rendering_type',
            field=models.IntegerField(choices=[(0, 'PDF'), (1, 'HTML')], default=0),
        ),
    ]
