# Generated by Django 3.0.3 on 2021-04-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20210406_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renderinvoicetemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
