# Generated by Django 3.0.3 on 2021-04-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20210410_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicetemplate',
            name='rendering_template',
        ),
        migrations.AddField(
            model_name='invoicetemplate',
            name='template',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
