# Generated by Django 3.0.3 on 2021-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20210410_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetemplate',
            name='template',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
