# Generated by Django 3.0.3 on 2021-04-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_auto_20210410_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_schedule_log_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
