# Generated by Django 3.0.3 on 2021-04-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_bill_bill_schedule_log_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulebilllog',
            name='activity_type_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
