# Generated by Django 3.0.3 on 2021-04-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_schedulebilllog_activity_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulebilllog',
            name='activity_type_id',
        ),
    ]
