# Generated by Django 3.0.3 on 2021-04-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_remove_schedulebilllog_activity_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='invoice_template',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
