# Generated by Django 3.0.3 on 2021-03-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldagentlivelocation',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 986708), null=True),
        ),
        migrations.AlterField(
            model_name='fieldagentlivelocation',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 986708), null=True),
        ),
        migrations.AlterField(
            model_name='logintrail',
            name='login_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 974710), null=True),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 746681), null=True),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 746681), null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 610605), null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 610605), null=True),
        ),
        migrations.AlterField(
            model_name='roleprivilege',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 978709), null=True),
        ),
        migrations.AlterField(
            model_name='roleprivilege',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 978709), null=True),
        ),
        migrations.AlterField(
            model_name='rolestatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 610605), null=True),
        ),
        migrations.AlterField(
            model_name='rolestatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 610605), null=True),
        ),
        migrations.AlterField(
            model_name='rolesubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 610605), null=True),
        ),
        migrations.AlterField(
            model_name='rolesubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 610605), null=True),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 610605), null=True),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 610605), null=True),
        ),
        migrations.AlterField(
            model_name='userarea',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 618605), null=True),
        ),
        migrations.AlterField(
            model_name='userarea',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 618605), null=True),
        ),
        migrations.AlterField(
            model_name='userbank',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 978709), null=True),
        ),
        migrations.AlterField(
            model_name='userbank',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 978709), null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 986708), null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 986708), null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 978709), null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 978709), null=True),
        ),
        migrations.AlterField(
            model_name='userleaves',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 986708), null=True),
        ),
        migrations.AlterField(
            model_name='userleaves',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 986708), null=True),
        ),
        migrations.AlterField(
            model_name='userprivilege',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 982710), null=True),
        ),
        migrations.AlterField(
            model_name='userprivilege',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 982710), null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 982710), null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 982710), null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 618605), null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 618605), null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 618605), null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 618605), null=True),
        ),
        migrations.AlterField(
            model_name='usersubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 622605), null=True),
        ),
        migrations.AlterField(
            model_name='usersubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 622605), null=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 982710), null=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 982710), null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 622605), null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 622605), null=True),
        ),
        migrations.AlterField(
            model_name='userutility',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 626605), null=True),
        ),
        migrations.AlterField(
            model_name='userutility',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 626605), null=True),
        ),
    ]
