# Generated by Django 3.0.11 on 2021-04-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20210331_0455'),
        ('userapp', '0002_auto_20210330_1649'),
    ]

    operations = [
    ]
