# Generated by Django 3.0.3 on 2021-03-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumerconsent',
            old_name='registration_subtype_id',
            new_name='consumer_category_id',
        ),
        migrations.RenameField(
            model_name='consumerconsent',
            old_name='registration_type_id',
            new_name='consumer_subcategory_id',
        ),
        migrations.RemoveField(
            model_name='consumerfaq',
            name='service_obj',
        ),
        migrations.AlterField(
            model_name='consumercategory',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 702709), null=True),
        ),
        migrations.AlterField(
            model_name='consumercategory',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumerconsent',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 894691), null=True),
        ),
        migrations.AlterField(
            model_name='consumerconsent',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumercreditrating',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 730708), null=True),
        ),
        migrations.AlterField(
            model_name='consumercreditrating',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 730708), null=True),
        ),
        migrations.AlterField(
            model_name='consumerdownpayment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 734682), null=True),
        ),
        migrations.AlterField(
            model_name='consumerdownpayment',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 734682), null=True),
        ),
        migrations.AlterField(
            model_name='consumerdownpayment',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 734682), null=True),
        ),
        migrations.AlterField(
            model_name='consumerfaq',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 898710), null=True),
        ),
        migrations.AlterField(
            model_name='consumerfaq',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumerloan',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 734682), null=True),
        ),
        migrations.AlterField(
            model_name='consumerloan',
            name='loan_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 734682), null=True),
        ),
        migrations.AlterField(
            model_name='consumerloan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 734682), null=True),
        ),
        migrations.AlterField(
            model_name='consumermaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 878682), null=True),
        ),
        migrations.AlterField(
            model_name='consumermaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 878682), null=True),
        ),
        migrations.AlterField(
            model_name='consumernotification',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 734682), null=True),
        ),
        migrations.AlterField(
            model_name='consumernotification',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 734682), null=True),
        ),
        migrations.AlterField(
            model_name='consumernotification',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 734682), null=True),
        ),
        migrations.AlterField(
            model_name='consumernotification',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 734682), null=True),
        ),
        migrations.AlterField(
            model_name='consumerofferdetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 738681), null=True),
        ),
        migrations.AlterField(
            model_name='consumerofferdetail',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 738681), null=True),
        ),
        migrations.AlterField(
            model_name='consumerofferdetail',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 738681), null=True),
        ),
        migrations.AlterField(
            model_name='consumerofferdetail',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 738681), null=True),
        ),
        migrations.AlterField(
            model_name='consumeroffermaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 742682), null=True),
        ),
        migrations.AlterField(
            model_name='consumeroffermaster',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 738681), null=True),
        ),
        migrations.AlterField(
            model_name='consumeroffermaster',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 738681), null=True),
        ),
        migrations.AlterField(
            model_name='consumerownership',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 882714), null=True),
        ),
        migrations.AlterField(
            model_name='consumerownership',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumerpersonaldetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 742682), null=True),
        ),
        migrations.AlterField(
            model_name='consumerpersonaldetail',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 742682), null=True),
        ),
        migrations.AlterField(
            model_name='consumerschememaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 886718), null=True),
        ),
        migrations.AlterField(
            model_name='consumerschememaster',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 886718), null=True),
        ),
        migrations.AlterField(
            model_name='consumerschememaster',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 886718), null=True),
        ),
        migrations.AlterField(
            model_name='consumerschememaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 886718), null=True),
        ),
        migrations.AlterField(
            model_name='consumerservicecontractdetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 882714), null=True),
        ),
        migrations.AlterField(
            model_name='consumerservicecontractdetail',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 882714), null=True),
        ),
        migrations.AlterField(
            model_name='consumerstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 886718), null=True),
        ),
        migrations.AlterField(
            model_name='consumerstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 886718), null=True),
        ),
        migrations.AlterField(
            model_name='consumersubcategory',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 702709), null=True),
        ),
        migrations.AlterField(
            model_name='consumersubcategory',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumersupport',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 898710), null=True),
        ),
        migrations.AlterField(
            model_name='consumersupport',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumertoken',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 886718), null=True),
        ),
        migrations.AlterField(
            model_name='consumertoken',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 886718), null=True),
        ),
        migrations.AlterField(
            model_name='financialdetails',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 890716), null=True),
        ),
        migrations.AlterField(
            model_name='financialdetails',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 890716), null=True),
        ),
        migrations.AlterField(
            model_name='offersubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 738681), null=True),
        ),
        migrations.AlterField(
            model_name='offertype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 738681), null=True),
        ),
        migrations.AlterField(
            model_name='schemetype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 890716), null=True),
        ),
        migrations.AlterField(
            model_name='schemetype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 890716), null=True),
        ),
        migrations.AlterField(
            model_name='servicerequestpriority',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 890716), null=True),
        ),
        migrations.AlterField(
            model_name='servicerequestpriority',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 890716), null=True),
        ),
        migrations.AlterField(
            model_name='servicerequeststatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 894691), null=True),
        ),
        migrations.AlterField(
            model_name='servicerequeststatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 894691), null=True),
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 894691), null=True),
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 894691), null=True),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 894691), null=True),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 894691), null=True),
        ),
    ]
