# Generated by Django 3.0.3 on 2021-05-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerconsent',
            name='name',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
