# Generated by Django 3.0.3 on 2021-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_auto_20210503_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumermaster',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consumermaster',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
