# Generated by Django 3.0.3 on 2021-04-02 12:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_consumerfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumeroffermaster',
            name='service_obj',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
