# Generated by Django 3.0.11 on 2021-04-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_auto_20210402_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerservicecontractdetail',
            name='state',
            field=models.IntegerField(choices=[(0, 'CONNECTED'), (1, 'DISCONNECTED'), (2, 'CREATED'), (3, 'APPROVED'), (4, 'REJECTED'), (5, 'HOLD')], default=2),
        ),
    ]
