# Generated by Django 3.0.3 on 2021-05-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_auto_20210512_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumermaster',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
