# Generated by Django 3.0.3 on 2021-03-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='long_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='short_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
