# Generated by Django 3.0.3 on 2021-03-10 07:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0018_auto_20210310_1314'),
        ('commonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_string', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status_code', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 722681), null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 614605), null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 614605), null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 706681), null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='log_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 706681), null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 706681), null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 698709), null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 698709), null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 594605), null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 594605), null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 594605), null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 594605), null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 710681), null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 710681), null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 594605), null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 594605), null=True),
        ),
        migrations.AlterField(
            model_name='departmentsubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 710681), null=True),
        ),
        migrations.AlterField(
            model_name='departmentsubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 710681), null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 614605), null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 614605), null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 602605), null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 602605), null=True),
        ),
        migrations.AlterField(
            model_name='documentsubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 598625), null=True),
        ),
        migrations.AlterField(
            model_name='documentsubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 598625), null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 710681), null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 710681), null=True),
        ),
        migrations.AlterField(
            model_name='formfactor',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 602605), null=True),
        ),
        migrations.AlterField(
            model_name='formfactor',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 602605), null=True),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 698709), null=True),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 698709), null=True),
        ),
        migrations.AlterField(
            model_name='global_lookup',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 674710), null=True),
        ),
        migrations.AlterField(
            model_name='global_lookup',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 674710), null=True),
        ),
        migrations.AlterField(
            model_name='integrationmaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 722681), null=True),
        ),
        migrations.AlterField(
            model_name='integrationmaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 722681), null=True),
        ),
        migrations.AlterField(
            model_name='integrationsubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 718682), null=True),
        ),
        migrations.AlterField(
            model_name='integrationsubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 718682), null=True),
        ),
        migrations.AlterField(
            model_name='integrationtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 718682), null=True),
        ),
        migrations.AlterField(
            model_name='integrationtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 718682), null=True),
        ),
        migrations.AlterField(
            model_name='lifecycle',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 714708), null=True),
        ),
        migrations.AlterField(
            model_name='lifecycle',
            name='log_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 714708), null=True),
        ),
        migrations.AlterField(
            model_name='lifecycle',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 714708), null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 602605), null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 602605), null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 710681), null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 710681), null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 710681), null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 710681), null=True),
        ),
        migrations.AlterField(
            model_name='notificationsubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 718682), null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 54, 243146), null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 54, 243146), null=True),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 718682), null=True),
        ),
        migrations.AlterField(
            model_name='premise',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 710681), null=True),
        ),
        migrations.AlterField(
            model_name='premise',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 710681), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 714708), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 714708), null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 590620), null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 590620), null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 618605), null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 594605), null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 594605), null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utility.UtilityMaster'),
        ),
        migrations.AlterField(
            model_name='stateconfiguration',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 714708), null=True),
        ),
        migrations.AlterField(
            model_name='stateconfiguration',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 714708), null=True),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 658678), null=True),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 658678), null=True),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 598625), null=True),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 598625), null=True),
        ),
        migrations.AlterField(
            model_name='transitionconfiguration',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 54, 239139), null=True),
        ),
        migrations.AlterField(
            model_name='transitionconfiguration',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 54, 239139), null=True),
        ),
        migrations.AlterField(
            model_name='workordersubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 722681), null=True),
        ),
        migrations.AlterField(
            model_name='workordersubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 722681), null=True),
        ),
        migrations.AlterField(
            model_name='workordertype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 722681), null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 614605), null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 614605), null=True),
        ),
    ]
