# Generated by Django 3.0.3 on 2021-04-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0002_auto_20210317_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
