# Generated by Django 3.0.11 on 2021-04-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0004_auto_20210421_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='last_auth_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
