# Generated by Django 3.0.3 on 2021-03-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='sa_time',
        ),
    ]
