# Generated by Django 3.0.11 on 2021-03-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='state',
            field=models.BigIntegerField(choices=[(0, 'CREATED'), (1, 'NOT ASSIGNED'), (2, 'ASSIGNED'), (3, 'IN PROGRESS'), (4, 'FAILED'), (5, 'ACCEPTED'), (6, 'REJECTED'), (7, 'COMPLETED'), (8, 'HOLD'), (9, 'CLOSED'), (10, 'ARCHIVED'), (11, 'REQUESTED')], default=1),
        ),
    ]
