# Generated by Django 3.0.3 on 2021-03-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaster',
            name='base_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordermaster',
            name='is_taxable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workordermaster',
            name='tax_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialname',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 6709), null=True),
        ),
        migrations.AlterField(
            model_name='materialname',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 6709), null=True),
        ),
        migrations.AlterField(
            model_name='materialsubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 6709), null=True),
        ),
        migrations.AlterField(
            model_name='materialsubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 6709), null=True),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 6709), null=True),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 6709), null=True),
        ),
        migrations.AlterField(
            model_name='scheduledappointment',
            name='assignment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 10710), null=True),
        ),
        migrations.AlterField(
            model_name='scheduledappointment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 10710), null=True),
        ),
        migrations.AlterField(
            model_name='scheduledappointment',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 10710), null=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 2709), null=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='sa_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 2709), null=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 2709), null=True),
        ),
        migrations.AlterField(
            model_name='serviceappointmentstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 2709), null=True),
        ),
        migrations.AlterField(
            model_name='serviceappointmentstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 2709), null=True),
        ),
        migrations.AlterField(
            model_name='serviceassignment',
            name='assignment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 2709), null=True),
        ),
        migrations.AlterField(
            model_name='serviceassignment',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 2709), null=True),
        ),
        migrations.AlterField(
            model_name='serviceassignment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 2709), null=True),
        ),
        migrations.AlterField(
            model_name='serviceassignment',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 2709), null=True),
        ),
        migrations.AlterField(
            model_name='workordermaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 998683), null=True),
        ),
        migrations.AlterField(
            model_name='workordermaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 998683), null=True),
        ),
        migrations.AlterField(
            model_name='workorderrule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 6709), null=True),
        ),
        migrations.AlterField(
            model_name='workorderrule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 6709), null=True),
        ),
    ]
