# Generated by Django 3.0.3 on 2021-03-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_auto_20210317_1139'),
        ('work_order', '0002_auto_20210317_1202'),
    ]

    operations = [
    ]
