# Generated by Django 3.0.3 on 2021-04-01 11:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_auto_20210317_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='completed_task_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='sa_rule',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
