# Generated by Django 3.0.3 on 2021-05-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_auto_20210503_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='actual_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='actual_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceassignment',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
