# Generated by Django 3.0.11 on 2021-05-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_auto_20210503_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaster',
            name='instructions',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='workordermaster',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
