# Generated by Django 3.0.3 on 2021-04-01 11:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_auto_20210401_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordermaster',
            name='json_obj',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workordermaster',
            name='service_obj',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
