# Generated by Django 3.0.11 on 2021-05-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0004_auto_20210513_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaster',
            name='completion_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
