# Generated by Django 3.0.3 on 2021-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0004_auto_20210517_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='frequency_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='recurring_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='repeat_every_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
