# Generated by Django 3.0.11 on 2021-05-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0005_workordermaster_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordermaster',
            name='completion_time',
            field=models.TimeField(null=True),
        ),
    ]
