# Generated by Django 3.0.3 on 2021-05-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0005_auto_20210518_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='cron_expression',
        ),
    ]
