# Generated by Django 3.0.11 on 2021-05-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0006_auto_20210514_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaster',
            name='expert_contact_no',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='workordermaster',
            name='expert_email',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='workordermaster',
            name='expert_name',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
