# Generated by Django 3.0.3 on 2021-05-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0006_auto_20210514_1734'),
        ('work_order', '0006_remove_serviceappointment_cron_expression'),
    ]

    operations = [
    ]
