# Generated by Django 3.0.11 on 2021-05-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0007_auto_20210524_1629'),
        ('work_order', '0007_merge_20210520_1252'),
    ]

    operations = [
    ]
