# Generated by Django 3.0.11 on 2021-06-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0008_merge_20210525_1113'),
    ]

    operations = [
    ]
