# Generated by Django 3.0.11 on 2021-06-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0009_merge_20210601_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='sa_description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
