# Generated by Django 3.0.3 on 2021-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=models.BigIntegerField(choices=[(0, 'CREATED'), (1, 'APPROVED'), (2, 'REJECTED'), (3, 'HOLD')], default=0),
        ),
        migrations.AlterField(
            model_name='registrationstatus',
            name='state',
            field=models.BigIntegerField(choices=[(0, 'CREATED'), (1, 'APPROVED'), (2, 'REJECTED'), (3, 'HOLD')], default=0),
        ),
    ]
