# Generated by Django 3.0.11 on 2021-05-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210424_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
