# Generated by Django 3.0.3 on 2021-03-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='bill_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 950714), null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 950714), null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='handover_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 950714), null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 950714), null=True),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 950714), null=True),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 950714), null=True),
        ),
        migrations.AlterField(
            model_name='storemaster',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 954682), null=True),
        ),
        migrations.AlterField(
            model_name='storemaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 954682), null=True),
        ),
        migrations.AlterField(
            model_name='storemaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 954682), null=True),
        ),
        migrations.AlterField(
            model_name='storetype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 950714), null=True),
        ),
        migrations.AlterField(
            model_name='storetype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 950714), null=True),
        ),
    ]
