# Generated by Django 3.0.10 on 2021-03-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetype',
            name='test_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
