# Generated by Django 3.0.10 on 2021-03-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storetype_test_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storetype',
            old_name='test_field',
            new_name='rename_field',
        ),
    ]
