# Generated by Django 3.0.10 on 2021-03-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210311_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storetype',
            name='rename_field',
        ),
    ]
