# Generated by Django 3.0.3 on 2021-03-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 994710), null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 994710), null=True),
        ),
        migrations.AlterField(
            model_name='tenderquotation',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 994710), null=True),
        ),
        migrations.AlterField(
            model_name='tenderquotation',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 994710), null=True),
        ),
        migrations.AlterField(
            model_name='tenderstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 990710), null=True),
        ),
        migrations.AlterField(
            model_name='tenderstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 990710), null=True),
        ),
        migrations.AlterField(
            model_name='tendertermsandcondition',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 994710), null=True),
        ),
        migrations.AlterField(
            model_name='tendertermsandcondition',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 994710), null=True),
        ),
        migrations.AlterField(
            model_name='tendertype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 990710), null=True),
        ),
        migrations.AlterField(
            model_name='tendertype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 990710), null=True),
        ),
        migrations.AlterField(
            model_name='tendervendor',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 994710), null=True),
        ),
        migrations.AlterField(
            model_name='tendervendor',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 994710), null=True),
        ),
    ]
