# Generated by Django 3.0.3 on 2021-03-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adassignstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 686708), null=True),
        ),
        migrations.AlterField(
            model_name='adassignstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 686708), null=True),
        ),
        migrations.AlterField(
            model_name='advertisementassignment',
            name='assigned_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 690709), null=True),
        ),
        migrations.AlterField(
            model_name='advertisementassignment',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 690709), null=True),
        ),
        migrations.AlterField(
            model_name='advertisementassignment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 690709), null=True),
        ),
        migrations.AlterField(
            model_name='advertisementassignment',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 690709), null=True),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 702709), null=True),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 702709), null=True),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 702709), null=True),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 702709), null=True),
        ),
        migrations.AlterField(
            model_name='advertisementsubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 706681), null=True),
        ),
        migrations.AlterField(
            model_name='advertisementsubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 706681), null=True),
        ),
        migrations.AlterField(
            model_name='advertisementtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 690709), null=True),
        ),
        migrations.AlterField(
            model_name='advertisementtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 690709), null=True),
        ),
        migrations.AlterField(
            model_name='advertstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 690709), null=True),
        ),
        migrations.AlterField(
            model_name='advertstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 690709), null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 702709), null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 702709), null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 702709), null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 702709), null=True),
        ),
        migrations.AlterField(
            model_name='campaigngroup',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 694681), null=True),
        ),
        migrations.AlterField(
            model_name='campaigngroup',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 694681), null=True),
        ),
        migrations.AlterField(
            model_name='campaignobjective',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 694681), null=True),
        ),
        migrations.AlterField(
            model_name='campaignobjective',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 694681), null=True),
        ),
        migrations.AlterField(
            model_name='campaignstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 694681), null=True),
        ),
        migrations.AlterField(
            model_name='campaignstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 694681), null=True),
        ),
        migrations.AlterField(
            model_name='campaignsubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 706681), null=True),
        ),
        migrations.AlterField(
            model_name='campaignsubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 706681), null=True),
        ),
        migrations.AlterField(
            model_name='campaigntype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 694681), null=True),
        ),
        migrations.AlterField(
            model_name='campaigntype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 694681), null=True),
        ),
    ]
