# Generated by Django 3.0.10 on 2021-03-10 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fsm.fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '__first__'),
        ('utility', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_string', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_request_no', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('consumer_no', models.CharField(blank=True, max_length=200, null=True)),
                ('consumer_service_master_id', models.BigIntegerField(blank=True, null=True)),
                ('service_type_id', models.BigIntegerField(blank=True, null=True)),
                ('service_sub_type_id', models.BigIntegerField(blank=True, null=True)),
                ('consumer_remark', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_remark', models.CharField(blank=True, max_length=500, null=True)),
                ('request_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('request_due_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('request_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('is_field_appointment', models.BooleanField(default=False)),
                ('state', models.BigIntegerField(choices=[(0, 'CREATED'), (1, 'ACCEPTED'), (2, 'REJECTED'), (3, 'IN PROGRESS'), (4, 'NOT ASSIGNED'), (5, 'ASSIGNED'), (6, 'COMPLETED'), (7, 'HOLD'), (8, 'CLOSED'), (9, 'FAILED'), (10, 'ARCHIVED')], default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.TenantMaster')),
                ('utility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.UtilityMaster')),
            ],
            bases=(models.Model, fsm.fsm.FiniteStateMachineMixin),
        ),
    ]
