# Generated by Django 3.0.3 on 2020-03-11 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0003_auto_20200311_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 6, 56, 51, 578385)),
        ),
    ]
