"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import environ
from v1.commonapp.views.secretcache import SecretManager

env = environ.Env()
# reading .env file
environ.Env.read_env()
USER = "U"
CONSUMER_USER = "C"
MODULE_LIST = ['CONSUMER_CARE','CX']
SUB_MODULE_LIST = ['CONSUMERS','CONSUMER_CARE_REGISTRATION','CX_SERVICE']
smart360_env = ''
secret = ""

if os.environ["smart360_env"] != 'dev':
    secret = SecretManager()


def get_secret_manager(key):
    if os.environ["smart360_env"] != 'dev':
        return secret.get_secret(key)


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = get_secret_manager(os.environ['smart360_env'] + "_secret_key")
print("=====Secret Key=====", SECRET_KEY)
# SECRET_KEY = get_secret_manager(os.environ['smart360_env'] + "_secret_key")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_twilio',
    'rest_framework',
    'storages',
    'corsheaders',
    'django_filters',
    'django_crontab',
    "fcm_django",
    'master',
    'v1.asset',
    'v1.billing',
    'v1.campaign',
    'v1.commonapp',
    'v1.consumer',
    'v1.complaint',
    'v1.service',
    'v1.contract',
    'v1.employee',
    'v1.meter_data_management',
    'v1.payment',
    'v1.payroll',
    'v1.registration',
    'v1.request',
    'v1.store',
    'v1.supplier',
    'v1.survey',
    'v1.userapp',
    'v1.tender',
    'v1.work_order',
    'v1.utility',
    'v1.tenant',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

AUTH_USER_MODEL = 'master.MasterUser'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

WSGI_APPLICATION = 'api.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'smart360',
        'USER': get_secret_manager(os.environ['smart360_env'] + "_database_user"),
        'PASSWORD': get_secret_manager(os.environ['smart360_env'] + "_database_password"),
        'HOST': get_secret_manager(os.environ['smart360_env'] + "_database_host"),
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

FCM_DJANGO_SETTINGS = {
    "APP_VERBOSE_NAME": "pushNotification",
    # default: _('FCM Django')
    "FCM_SERVER_KEY": "AIzaSyC3bCWia94LRa-Oj2FdOnYxS1k4kSo4a9A",
    # true if you want to have only one active device per registered user at a time
    # default: False
    "ONE_DEVICE_PER_USER": False,
    # devices to which notifications cannot be sent,
    # are deleted upon receiving error response from FCM
    # default: False
    "DELETE_INACTIVE_DEVICES": True,
}

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DISPLAY_DATE_FORMAT = "%d-%b-%Y"

DISPLAY_DATE_TIME_FORMAT = "%d/%m/%Y %H:%M:%S"

INPUT_DATE_FORMAT = "%d-%b-%Y"

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'file': {
#             'level': 'INFO',
#             'class': 'logging.FileHandler',
#             'filename': BASE_DIR + '/debug.log',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': 'INFO',
#         },
#     },
# }

# Cronjob configuration
CRONJOBS = [
    # Todo Add File Path To Save Log File
    # Cron Use For MDM Module Start
    ('0 22 * * *', 'v1.meter_data_management.task.schedule_log.schedule_log',
     '>> /home/aki/Aki/Projects/Smart360-app/api/schedule_log.log'),
    ('*/30 * * * *', 'v1.meter_data_management.task.validation_assignment.validation_assignment',
     '>> /home/aki/Aki/Projects/Smart360-app/api/validation_assignment.log'),
    ('0 23 * * *', 'v1.meter_data_management.task.smart_meter.smart_meter',
     '>> /home/aki/Aki/Projects/Smart360-app/api/smart_meter.log'),
    ('0 23 * * *', 'v1.meter_data_management.task.spot_bill.spot_bill',
     '>> /home/aki/Aki/Projects/Smart360-app/api/spot_bill.log'),
    # Cron Use For MDM Module End
]

# Amazon s3 Configuration
AWS_ACCESS_KEY_ID = ''
AWS_SECRET_ACCESS_KEY = ''
AWS_STORAGE_BUCKET_NAME = ''
AWS_S3_ENDPOINT_URL = ''
AWS_DEFAULT_ACL = None
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_LOCATION = ''
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
MEDIA_URL = 'https://%s/%s/' % (AWS_S3_ENDPOINT_URL, AWS_LOCATION)

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = get_secret_manager(os.environ['smart360_env'] + "_email_host_user")
EMAIL_HOST_PASSWORD = get_secret_manager(os.environ['smart360_env'] + "_email_host_password")

# SMS configuration
TWILIO_ACCOUNT_SID = get_secret_manager(os.environ['smart360_env'] + "_twilio_account_id")
TWILIO_AUTH_TOKEN = get_secret_manager(os.environ['smart360_env'] + "_twilio_auth_token")

AUTHENTICATION_BACKENDS = ( 
                            'master.backends.AuthBackend',
                            'django.contrib.auth.backends.ModelBackend',
                        )

AWS_ACCESS_KEY = 'AKIARUU5RUAA6JXDZZGR'
AWS_SECRET_KEY = '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'
AWS_S3_BUCKET = 'smart360-bucket'