# Generated by Django 3.0.11 on 2021-05-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='settlement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
