# Generated by Django 3.0.11 on 2021-03-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentchannel',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
