# Generated by Django 3.0.3 on 2021-03-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cheque_dd_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 930715), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 934717), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 930715), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 934717), null=True),
        ),
        migrations.AlterField(
            model_name='paymentchannel',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 926682), null=True),
        ),
        migrations.AlterField(
            model_name='paymentchannel',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 926682), null=True),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 930715), null=True),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 930715), null=True),
        ),
        migrations.AlterField(
            model_name='paymentsource',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 930715), null=True),
        ),
        migrations.AlterField(
            model_name='paymentsource',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 930715), null=True),
        ),
        migrations.AlterField(
            model_name='paymentsubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 930715), null=True),
        ),
        migrations.AlterField(
            model_name='paymentsubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 930715), null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 934717), null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='settlement_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 934717), null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 934717), null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 934717), null=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 930715), null=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 930715), null=True),
        ),
    ]
