# Generated by Django 3.0.3 on 2021-03-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 970682), null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 970682), null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 970682), null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 970682), null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 970682), null=True),
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='assigned_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 974710), null=True),
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 974710), null=True),
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 974710), null=True),
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 974710), null=True),
        ),
        migrations.AlterField(
            model_name='surveyconsumer',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 970682), null=True),
        ),
        migrations.AlterField(
            model_name='surveyconsumer',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 970682), null=True),
        ),
        migrations.AlterField(
            model_name='surveyobjective',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 970682), null=True),
        ),
        migrations.AlterField(
            model_name='surveyobjective',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 970682), null=True),
        ),
        migrations.AlterField(
            model_name='surveystatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 970682), null=True),
        ),
        migrations.AlterField(
            model_name='surveystatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 970682), null=True),
        ),
        migrations.AlterField(
            model_name='surveysubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 970682), null=True),
        ),
        migrations.AlterField(
            model_name='surveysubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 970682), null=True),
        ),
        migrations.AlterField(
            model_name='surveytransactionstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 974710), null=True),
        ),
        migrations.AlterField(
            model_name='surveytransactionstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 974710), null=True),
        ),
        migrations.AlterField(
            model_name='surveytype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 966709), null=True),
        ),
        migrations.AlterField(
            model_name='surveytype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 966709), null=True),
        ),
    ]
