# Generated by Django 3.0.3 on 2021-03-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 910682), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 910682), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 910682), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 910682), null=True),
        ),
        migrations.AlterField(
            model_name='contractdemand',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 910682), null=True),
        ),
        migrations.AlterField(
            model_name='contractdemand',
            name='demand_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 910682), null=True),
        ),
        migrations.AlterField(
            model_name='contractdemand',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 910682), null=True),
        ),
        migrations.AlterField(
            model_name='contractdemand',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 910682), null=True),
        ),
        migrations.AlterField(
            model_name='contractperiod',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 906715), null=True),
        ),
        migrations.AlterField(
            model_name='contractperiod',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 906715), null=True),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 906715), null=True),
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 906715), null=True),
        ),
        migrations.AlterField(
            model_name='contractsubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 910682), null=True),
        ),
        migrations.AlterField(
            model_name='contractsubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 910682), null=True),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 906715), null=True),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 906715), null=True),
        ),
        migrations.AlterField(
            model_name='termsandcondition',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 910682), null=True),
        ),
        migrations.AlterField(
            model_name='termsandcondition',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 910682), null=True),
        ),
    ]
