# Generated by Django 3.0.11 on 2021-06-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_auto_20210423_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
