#!/bin/bash

echo "################################################## Installing dependencies############################################"
source  /home/ubuntu/smart360/smart360venv/bin/activate
pip install django gunicorn psycopg2-binary
sudo -H apt install -y libcurl4-openssl-dev libssl-dev python3-pycurl
pip install -r /home/ubuntu/smart360/api/requirement.txt
sudo -H pip install django gunicorn psycopg2-binary
sudo -H pip install -r /home/ubuntu/smart360/api/requirement.txt
echo "################################################## Setting permission ############################################"
sudo chown ubuntu:ubuntu -R /home/ubuntu/smart360
echo "################################################## Setting environment file ############################################"
sudo touch /home/ubuntu/smart360/api/.env
sudo chmod 777 /home/ubuntu/smart360/api/.env
echo "smart360_env=$DEPLOYMENT_GROUP_NAME" >> /home/ubuntu/smart360/api/.env
# sed -i "s/smart360_env = ''/smart360_env = \'$DEPLOYMENT_GROUP_NAME\'/g" /home/ubuntu/smart360/api/api/settings.py

echo "################################################## Running makemigrations ############################################"
# export smart360_env="$DEPLOYMENT_GROUP_NAME"

echo "################################################## Running migrate command ############################################" 


echo "################################################## After fake ############################################"

cd /home/ubuntu/smart360/api && sudo python3 manage.py migrate

echo "################################################## Loading data ############################################"

cd /home/ubuntu/smart360/api && sudo python3 manage.py loaddata data.json

echo "############################## Successfully load data ######################################################"

cd /home/ubuntu/smart360/api && sudo python3 manage.py showmigrations

echo "############################## SHOWING MIGRATIONS ######################################################"
echo "############################## SHOWING MIGRATIONS ######################################################"
# cd /home/ubuntu/smart360/api && cat <(echo "yes") - | python3 manage.py collectstatic