#!/bin/bash

rm -rf /home/ubuntu/smart360/api
rm /home/ubuntu/smart360/.gitignore
rm /home/ubuntu/smart360/README.md
rm /home/ubuntu/smart360/__init__.py
rm /home/ubuntu/smart360/buildspec.yml
rm /home/ubuntu/smart360/appspec.yml