#!/bin/bash

sudo rm -rf /home/ubuntu/smart360/api
sudo rm /home/ubuntu/smart360/.gitignore
sudo rm /home/ubuntu/smart360/README.md
sudo rm /home/ubuntu/smart360/__init__.py
sudo rm /home/ubuntu/smart360/buildspec.yml
sudo rm /home/ubuntu/smart360/appspec.yml