# Generated by Django 3.0.3 on 2021-03-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 954682), null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 954682), null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 958710), null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 958710), null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 606605), null=True),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 958710), null=True),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 958710), null=True),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='invoice_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 958710), null=True),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 958710), null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='cheque_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 958710), null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 958710), null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='dd_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 958710), null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 958710), null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 958710), null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 962742), null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 962742), null=True),
        ),
        migrations.AlterField(
            model_name='supplierservice',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 962742), null=True),
        ),
        migrations.AlterField(
            model_name='supplierservice',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 962742), null=True),
        ),
        migrations.AlterField(
            model_name='supplierstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 962742), null=True),
        ),
        migrations.AlterField(
            model_name='supplierstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 962742), null=True),
        ),
        migrations.AlterField(
            model_name='suppliersubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 966709), null=True),
        ),
        migrations.AlterField(
            model_name='suppliersubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 966709), null=True),
        ),
        migrations.AlterField(
            model_name='suppliertype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 962742), null=True),
        ),
        migrations.AlterField(
            model_name='suppliertype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 56, 962742), null=True),
        ),
        migrations.AlterField(
            model_name='supsersubcategory',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 278711), null=True),
        ),
        migrations.AlterField(
            model_name='supsersubcategory',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 278711), null=True),
        ),
        migrations.AlterField(
            model_name='supservicecategory',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 274710), null=True),
        ),
        migrations.AlterField(
            model_name='supservicecategory',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 13, 13, 57, 274710), null=True),
        ),
    ]
