# Generated by Django 3.0.11 on 2021-05-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20210423_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmaster',
            name='tenant_short_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
