# Generated by Django 3.0.3 on 2021-03-08 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20210308_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbankdetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 616779), null=True),
        ),
        migrations.AlterField(
            model_name='tenantbankdetail',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 616779), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcity',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 47, 3606), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcountry',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 47, 3606), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcurrency',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 665320), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcurrency',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 665320), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 668312), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 667314), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='invoice_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 667314), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 668312), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoicepayment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 668312), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoicepayment',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 668312), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 47, 6060), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 47, 6060), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 670306), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 670306), null=True),
        ),
        migrations.AlterField(
            model_name='tenantregion',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 942967), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 47, 5062), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 47, 5062), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 47, 5062), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubmodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 669309), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubmodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 669309), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 667314), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 667314), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplan',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 663325), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 663325), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 665320), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 664337), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 665320), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsummaryonmonthlybasis',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 671304), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsummaryonmonthlybasis',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 25, 49, 671304), null=True),
        ),
    ]
