# Generated by Django 3.0.11 on 2021-05-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_remove_tenantmaster_tenant_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantstatus',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
