# Generated by Django 3.0.3 on 2021-03-08 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_auto_20210308_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbankdetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 736756), null=True),
        ),
        migrations.AlterField(
            model_name='tenantbankdetail',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 736756), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcity',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 150080), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcountry',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 150080), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcurrency',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 783075), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcurrency',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 783075), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 786067), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 786067), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='invoice_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 786067), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 786067), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoicepayment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 786067), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoicepayment',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 786067), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 152075), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 152075), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 788062), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 788062), null=True),
        ),
        migrations.AlterField(
            model_name='tenantregion',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 43, 56915), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 151077), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 152075), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 152075), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubmodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 787065), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubmodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 787065), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 785070), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 785070), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplan',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 781080), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 781080), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 782078), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 782078), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 782078), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsummaryonmonthlybasis',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 789059), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsummaryonmonthlybasis',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 789059), null=True),
        ),
    ]
