# Generated by Django 3.0.3 on 2021-03-08 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_auto_20210308_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbankdetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 96657), null=True),
        ),
        migrations.AlterField(
            model_name='tenantbankdetail',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 96657), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcity',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 39, 503163), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcountry',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 39, 504161), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcurrency',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 143517), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcurrency',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 143517), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 145515), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 145515), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='invoice_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 145515), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 145515), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoicepayment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 146511), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoicepayment',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 146511), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 39, 506155), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 39, 506155), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 147511), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 147511), null=True),
        ),
        migrations.AlterField(
            model_name='tenantregion',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 403790), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 39, 504161), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 39, 505158), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 39, 505158), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubmodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 146511), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubmodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 146511), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 144483), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 144483), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplan',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 141500), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 141500), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 142518), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 142518), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 142518), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsummaryonmonthlybasis',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 148506), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsummaryonmonthlybasis',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 32, 42, 148506), null=True),
        ),
    ]
