# Generated by Django 3.0.3 on 2021-03-08 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_auto_20210308_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbankdetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 67523), null=True),
        ),
        migrations.AlterField(
            model_name='tenantbankdetail',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 67523), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcity',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 22, 494298), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcountry',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 22, 495295), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcurrency',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 116040), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcurrency',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 116040), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 119032), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 119032), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='invoice_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 119032), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 119032), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoicepayment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 120029), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoicepayment',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 120029), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 22, 497290), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 22, 497290), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 121769), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 121769), null=True),
        ),
        migrations.AlterField(
            model_name='tenantregion',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 388924), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 22, 496292), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 22, 496292), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 22, 496292), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubmodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 120771), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubmodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 120771), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 118035), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 118035), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplan',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 114044), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 114044), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 115043), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 115043), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 115043), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsummaryonmonthlybasis',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 121769), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsummaryonmonthlybasis',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 33, 25, 121769), null=True),
        ),
    ]
