# Generated by Django 3.0.3 on 2021-03-08 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0019_auto_20210308_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbankdetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 910816), null=True),
        ),
        migrations.AlterField(
            model_name='tenantbankdetail',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 910816), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcity',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 53, 308352), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcountry',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 53, 309350), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcurrency',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 959995), null=True),
        ),
        migrations.AlterField(
            model_name='tenantcurrency',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 959995), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 961990), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 961990), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='invoice_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 961990), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 961990), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoicepayment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 961990), null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvoicepayment',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 961990), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 53, 311344), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 53, 311344), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 963985), null=True),
        ),
        migrations.AlterField(
            model_name='tenantmodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 963985), null=True),
        ),
        migrations.AlterField(
            model_name='tenantregion',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 56, 249023), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 53, 310347), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 53, 311344), null=True),
        ),
        migrations.AlterField(
            model_name='tenantstatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 53, 311344), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubmodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 962987), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubmodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 962987), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 960992), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 960992), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplan',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 958001), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 958001), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 958998), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 958998), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscriptionplanrate',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 958998), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsummaryonmonthlybasis',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 964982), null=True),
        ),
        migrations.AlterField(
            model_name='tenantsummaryonmonthlybasis',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 48, 55, 964982), null=True),
        ),
    ]
