# Generated by Django 3.0.3 on 2021-03-08 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitycurrency',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 766203), null=True),
        ),
        migrations.AlterField(
            model_name='utilitycurrency',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 766203), null=True),
        ),
        migrations.AlterField(
            model_name='utilitydepartmentsubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 777741), null=True),
        ),
        migrations.AlterField(
            model_name='utilitydepartmentsubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 777741), null=True),
        ),
        migrations.AlterField(
            model_name='utilitydepartmenttype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 776744), null=True),
        ),
        migrations.AlterField(
            model_name='utilitydepartmenttype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 776744), null=True),
        ),
        migrations.AlterField(
            model_name='utilitydocumenttype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 163046), null=True),
        ),
        migrations.AlterField(
            model_name='utilitydocumenttype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 163046), null=True),
        ),
        migrations.AlterField(
            model_name='utilityholidaycalendar',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 775745), null=True),
        ),
        migrations.AlterField(
            model_name='utilityholidaycalendar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 11, 27, 42, 775745)),
        ),
        migrations.AlterField(
            model_name='utilityholidaycalendar',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 775745), null=True),
        ),
        migrations.AlterField(
            model_name='utilityleavetype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 775745), null=True),
        ),
        migrations.AlterField(
            model_name='utilityleavetype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 775745), null=True),
        ),
        migrations.AlterField(
            model_name='utilitymandetoryfields',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 765205), null=True),
        ),
        migrations.AlterField(
            model_name='utilitymandetoryfields',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 765205), null=True),
        ),
        migrations.AlterField(
            model_name='utilitymaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 154069), null=True),
        ),
        migrations.AlterField(
            model_name='utilitymodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 258305), null=True),
        ),
        migrations.AlterField(
            model_name='utilitymodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 258305), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymentchannel',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 237845), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymentchannel',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 237845), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymentmode',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 774424), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymentmode',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 774424), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymentsubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 773558), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymentsubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 773558), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymenttype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 772561), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymenttype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 772561), null=True),
        ),
        migrations.AlterField(
            model_name='utilityproduct',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 223882), null=True),
        ),
        migrations.AlterField(
            model_name='utilityregion',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 159057), null=True),
        ),
        migrations.AlterField(
            model_name='utilityregion',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 159057), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicecontractmaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 275257), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicecontractmaster',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 275257), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicecontractmaster',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 275257), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicecontractmaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 275257), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicecontracttemplate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 766203), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicecontracttemplate',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 767201), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicemaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 767201), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicemaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 767201), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicenumberformat',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 467908), null=True),
        ),
        migrations.AlterField(
            model_name='utilityserviceplan',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 768198), null=True),
        ),
        migrations.AlterField(
            model_name='utilityserviceplan',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 768198), null=True),
        ),
        migrations.AlterField(
            model_name='utilityserviceplan',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 768198), null=True),
        ),
        migrations.AlterField(
            model_name='utilityserviceplan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 768198), null=True),
        ),
        migrations.AlterField(
            model_name='utilityserviceplanrate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 769732), null=True),
        ),
        migrations.AlterField(
            model_name='utilityserviceplanrate',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 769732), null=True),
        ),
        migrations.AlterField(
            model_name='utilitystatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 770690), null=True),
        ),
        migrations.AlterField(
            model_name='utilitystatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 770690), null=True),
        ),
        migrations.AlterField(
            model_name='utilitysubmodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 272266), null=True),
        ),
        migrations.AlterField(
            model_name='utilitysubmodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 40, 272266), null=True),
        ),
        migrations.AlterField(
            model_name='utilityusagesummary',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 771562), null=True),
        ),
        migrations.AlterField(
            model_name='utilityusagesummary',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 771562), null=True),
        ),
        migrations.AlterField(
            model_name='utilityworkinghours',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 779085), null=True),
        ),
        migrations.AlterField(
            model_name='utilityworkinghours',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 779085), null=True),
        ),
        migrations.AlterField(
            model_name='utilityworkordersubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 753602), null=True),
        ),
        migrations.AlterField(
            model_name='utilityworkordersubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 753602), null=True),
        ),
        migrations.AlterField(
            model_name='utilityworkordertype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 752605), null=True),
        ),
        migrations.AlterField(
            model_name='utilityworkordertype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 27, 42, 752605), null=True),
        ),
    ]
