# Generated by Django 3.0.11 on 2021-05-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_auto_20210424_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilityworkinghours',
            name='sun_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='utilityworkinghours',
            name='sun_start',
            field=models.TimeField(null=True),
        ),
    ]
