# Generated by Django 3.0.11 on 2021-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_auto_20210510_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitymaster',
            name='document_generated_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
