# Generated by Django 3.0.11 on 2021-03-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_remove_utilitypaymentchannel_utility_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitymaster',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
