# Generated by Django 3.0.11 on 2021-05-27 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_auto_20210526_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilityholidaycalendar',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
