# Generated by Django 3.0.11 on 2021-04-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0007_auto_20210412_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilityservicecontractmaster',
            name='duration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
