# Generated by Django 3.0.11 on 2021-04-23 05:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_auto_20210412_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilityservicecontractmaster',
            name='service_obj',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
