# Generated by Django 3.0.3 on 2021-03-08 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_auto_20210308_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitycurrency',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 354006), null=True),
        ),
        migrations.AlterField(
            model_name='utilitycurrency',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 354006), null=True),
        ),
        migrations.AlterField(
            model_name='utilitydepartmentsubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 367143), null=True),
        ),
        migrations.AlterField(
            model_name='utilitydepartmentsubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 367143), null=True),
        ),
        migrations.AlterField(
            model_name='utilitydepartmenttype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 366348), null=True),
        ),
        migrations.AlterField(
            model_name='utilitydepartmenttype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 366348), null=True),
        ),
        migrations.AlterField(
            model_name='utilitydocumenttype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 771318), null=True),
        ),
        migrations.AlterField(
            model_name='utilitydocumenttype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 771318), null=True),
        ),
        migrations.AlterField(
            model_name='utilityholidaycalendar',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 364352), null=True),
        ),
        migrations.AlterField(
            model_name='utilityholidaycalendar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 11, 38, 10, 364352)),
        ),
        migrations.AlterField(
            model_name='utilityholidaycalendar',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 364352), null=True),
        ),
        migrations.AlterField(
            model_name='utilityleavetype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 364352), null=True),
        ),
        migrations.AlterField(
            model_name='utilityleavetype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 364352), null=True),
        ),
        migrations.AlterField(
            model_name='utilitymandetoryfields',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 352446), null=True),
        ),
        migrations.AlterField(
            model_name='utilitymandetoryfields',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 352446), null=True),
        ),
        migrations.AlterField(
            model_name='utilitymaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 760385), null=True),
        ),
        migrations.AlterField(
            model_name='utilitymodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 868341), null=True),
        ),
        migrations.AlterField(
            model_name='utilitymodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 868341), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymentchannel',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 846400), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymentchannel',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 846400), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymentmode',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 363056), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymentmode',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 363056), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymentsubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 362224), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymentsubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 362224), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymenttype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 361227), null=True),
        ),
        migrations.AlterField(
            model_name='utilitypaymenttype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 361227), null=True),
        ),
        migrations.AlterField(
            model_name='utilityproduct',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 832437), null=True),
        ),
        migrations.AlterField(
            model_name='utilityregion',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 766362), null=True),
        ),
        migrations.AlterField(
            model_name='utilityregion',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 766362), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicecontractmaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 884299), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicecontractmaster',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 884299), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicecontractmaster',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 884299), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicecontractmaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 884299), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicecontracttemplate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 355006), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicecontracttemplate',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 355006), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicemaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 356003), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicemaster',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 356003), null=True),
        ),
        migrations.AlterField(
            model_name='utilityservicenumberformat',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 8, 33918), null=True),
        ),
        migrations.AlterField(
            model_name='utilityserviceplan',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 357015), null=True),
        ),
        migrations.AlterField(
            model_name='utilityserviceplan',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 357015), null=True),
        ),
        migrations.AlterField(
            model_name='utilityserviceplan',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 357015), null=True),
        ),
        migrations.AlterField(
            model_name='utilityserviceplan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 357015), null=True),
        ),
        migrations.AlterField(
            model_name='utilityserviceplanrate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 358344), null=True),
        ),
        migrations.AlterField(
            model_name='utilityserviceplanrate',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 358344), null=True),
        ),
        migrations.AlterField(
            model_name='utilitystatus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 359329), null=True),
        ),
        migrations.AlterField(
            model_name='utilitystatus',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 359329), null=True),
        ),
        migrations.AlterField(
            model_name='utilitysubmodule',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 881307), null=True),
        ),
        migrations.AlterField(
            model_name='utilitysubmodule',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 7, 881307), null=True),
        ),
        migrations.AlterField(
            model_name='utilityusagesummary',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 360228), null=True),
        ),
        migrations.AlterField(
            model_name='utilityusagesummary',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 360228), null=True),
        ),
        migrations.AlterField(
            model_name='utilityworkinghours',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 368021), null=True),
        ),
        migrations.AlterField(
            model_name='utilityworkinghours',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 368021), null=True),
        ),
        migrations.AlterField(
            model_name='utilityworkordersubtype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 342911), null=True),
        ),
        migrations.AlterField(
            model_name='utilityworkordersubtype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 342911), null=True),
        ),
        migrations.AlterField(
            model_name='utilityworkordertype',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 341913), null=True),
        ),
        migrations.AlterField(
            model_name='utilityworkordertype',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 11, 38, 10, 341913), null=True),
        ),
    ]
