# Generated by Django 3.0.3 on 2020-03-11 06:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_token'),
        ('masterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='userapp.User'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 6, 55, 3, 768193)),
        ),
    ]
