# Generated by Django 3.0.3 on 2020-03-11 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_token'),
        ('masterapp', '0002_auto_20200311_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='userapp.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privilege',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 6, 56, 26, 152328)),
        ),
    ]
